name: Bash Linter

on:
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: Run ShellCheck on ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Check out repositiry
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: './scripts'
